//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shampaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellFactor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellFactor()
        {
            this.SellFactorItems = new HashSet<SellFactorItem>();
        }
    
        public long Id { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime Date { get; set; }
        public long PersonId { get; set; }
        public string Description { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellFactorItem> SellFactorItems { get; set; }
    }
}
